spring.application.name=DesafioTecnicoMuralis2026

#Config para que o Spring identifique a .env
spring.config.import = optional:file:.env[.properties]

#Configs do JPA
spring.jpa.hibernate.ddl-auto=update